name: "CI"
on: [push]
jobs: 
  build-and-test:
    name: Build and Test
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Format
      - name: Configure 
        uses: actions-rs/toolchain@v
        with: 
          command: fmt 
          args: --all -- --check
      - name: Clippy 
        uses: actions-rs/cargo@v1 
        with: 
          command: clippy 
          args: --all-targets --all-features -- -D warnings
      - name: Run Tests
        uses: actions-rs/cargo@v1
        with: 
          command: test
